# Generated by Django 2.2.1 on 2019-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
