# Generated by Django 2.2.1 on 2019-09-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_seat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('cmnd', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('born', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time_train', models.TimeField()),
                ('end_time_train', models.TimeField()),
                ('type_ticket', models.IntegerField(default=0)),
                ('price_origin', models.FloatField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_seat', models.IntegerField(default=0)),
                ('is_debt', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('pay_type', models.IntegerField(default=0)),
                ('price_origin', models.FloatField(default=0, max_length=20)),
                ('price', models.FloatField(default=0, max_length=20)),
                ('time_check_in', models.DateTimeField()),
                ('role', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Train')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_origin', models.FloatField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='PayDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('money_spend', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('money', models.FloatField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.User')),
            ],
        ),
    ]
